import {Timestamp} from "firebase-admin/firestore";

export type WorkoutInsight = {
    "id": string,
    "date": Timestamp,
    "workout_count": number,
    "total_sets": number,
    "total_repetitions": number,
    "total_weight": number,
    "total_run_distance": number,
    "total_run_duration": number,
    "total_elevation": number,
    "total_swim_distance": number,
    "total_swim_duration": number,
    "total_laps": number,
    "exercise_id_most_activities": string,
    "exercise_occurrence_counts": { [key: string]: number }
    "activity_id_most_elevation": string,
    "activity_id_most_laps": string,
    "activity_id_most_run_distance": string,
    "activity_id_most_run_duration": string,
    "activity_id_most_swim_distance": string,
    "activity_id_most_swim_duration": string,
    "activity_id_most_repetitions": string,
    "activity_id_most_weight": string,
    "highest_weight_value": number,
    "highest_weight_set_index": number,
    "highest_laps_value": number,
    "highest_laps_set_index": number,
    "highest_run_distance_value": number,
    "highest_run_distance_set_index": number,
    "highest_swim_distance_value": number,
    "highest_swim_distance_set_index": number,
    "highest_elevation_value": number,
    "highest_elevation_set_index": number,
    "highest_run_duration_value": number,
    "highest_run_duration_set_index": number,
    "highest_swim_duration_value": number,
    "highest_swim_duration_set_index": number,
    "highest_repetitions_value": number,
    "highest_repetitions_set_index": number,
    "exercise_set_counts": { [key: string]: number },
    "exercise_id_most_sets": string
}
